modLoader="javafml"
loaderVersion="[31,)"
logoFile="logo.png"
authors="Farcr & Bagel"
credits="hatsondogs, five"

[[mods]]
    modId="environmental"
    version="${file.jarVersion}"
    displayName="Environmental"
    description='''
    Expanding the environment. New wood, new blocks, new friends.
    '''

[[dependencies.environmental]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.environmental]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.environmental]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.6,)"
    ordering="AFTER"
    side="BOTH"