modLoader="javafml"
loaderVersion="[32,)"
logoFile="logo.png"
authors="Farcr & Bagel"
credits="hatsondogs, five"

[[mods]]
    modId="environmental"
    version="${file.jarVersion}"
    displayName="Environmental"
    description='''
    Expanding the environment. New wood, new blocks, new friends.
    '''

[[dependencies.environmental]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.environmental]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.environmental]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"