modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/minecraftabnormals/Environmental/issues"
license="https://github.com/minecraftabnormals/Environmental/blob/master/LICENSE.txt"

[[mods]]
    modId="${id}"
    version="${version}"
    displayName="${name}"
    logoFile="logo.png"
    authors="bageldotjpg, Farcr"
    credits="hatsondogs, Jackson, Ocelot, Echolite, and five"
    description='''Expanding the environment. New wood, new blocks, new friends.'''

[[dependencies.environmental]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.88,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.environmental]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.environmental]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.0.7,)"
    ordering="AFTER"
    side="BOTH"